package command

// Это команды от сервера
const (
	RDB Type = "rdb"

	Ping      Type = "ping"
	Select    Type = "select"
	Zadd      Type = "zadd"
	Sadd      Type = "sadd"
	Zrem      Type = "zrem"
	Delete    Type = "delete"
	Empty     Type = "empty"
	Undefined Type = "undefined"

	Lpush  Type = "lpush"
	LpushX Type = "lpushx"
	Rpush  Type = "rpush"
	RpushX Type = "rpushx"

	Rpop      Type = "rpop"
	RpopLpush Type = "rpoplpush"
	Lpop      Type = "lpop"

	ZremRangeByLex   Type = "zremrangebylex"
	ZremRangeByRank  Type = "zremrangebyrank"
	ZremRangeByScore Type = "zremrangebyscore"

	ZunionStore  Type = "zunionstore"
	ZincrBy      Type = "zincrby"
	SdiffStore   Type = "sdiffstore"
	SinterStore  Type = "sinterstore"
	Smove        Type = "smove"
	SunionStore  Type = "sunionstore"
	Srem         Type = "srem"
	Set          Type = "set"
	SetBit       Type = "setbit"
	Append       Type = "append"
	BitField     Type = "bitfield"
	BitOp        Type = "bitop"
	Decr         Type = "decr"
	DecrBy       Type = "decrby"
	Incr         Type = "incr"
	IncrBy       Type = "incrby"
	IncrByFloat  Type = "incrbyfloat"
	GetSet       Type = "getset"
	Mset         Type = "mset"
	MsetNX       Type = "msetnx"
	SetEX        Type = "setex"
	SetNX        Type = "setnx"
	SetRange     Type = "setrange"
	BlPop        Type = "blpop"
	BrPop        Type = "brpop"
	BrPopLpush   Type = "brpoplpush"
	Linsert      Type = "linsert"
	Lrem         Type = "lrem"
	Lset         Type = "lset"
	Ltrim        Type = "ltrim"
	Expire       Type = "expire"
	ExpireAt     Type = "expireat"
	Pexpire      Type = "pexpire"
	PexpireAt    Type = "pexpireat"
	Move         Type = "move"
	Persist      Type = "persist"
	Rename       Type = "rename"
	Restore      Type = "restore"
	Hset         Type = "hset"
	HsetNx       Type = "hset"
	HmSet        Type = "hmset"
	HincrBy      Type = "hincrby"
	HincrByFloat Type = "hincrby"
	PfAdd        Type = "pfadd"
	PfMerge      Type = "pfmerge"
	PsetX        Type = "psetx"
)

// Type это тип команды
type Type string
